const express = require('express');
const router = express.Router();
const userRouter = require('./user.router');
const imageRouter = require('./image.router');
const brandRouter = require('./brand.router');
const categoryRouter = require('./category.router');
const orderRouter = require('./order.router');
const productRouter = require('./product.router');
const reviewRouter = require('./review.router');
const serialProductRouter = require('./serialProduct.router');
const warrantyRouter = require('./warranty.router');
const repairRequestRouter = require('./repairRequest.router');
const groupCustomerRouter = require('./groupCustomer.router');
router.use('/user', userRouter);
router.use('/image', imageRouter);
router.use('/brand', brandRouter);
router.use('/category', categoryRouter);
router.use('/order', orderRouter);
router.use('/product', productRouter);
router.use('/review', reviewRouter);
router.use('/serial-product', serialProductRouter);
router.use('/warranty', warrantyRouter);
router.use('/repair-request', repairRequestRouter);
router.use('/group-customer', groupCustomerRouter);
module.exports = router;
